### ISSUE TITLE
Duplicate Android symbols generated

### ISSUE THREAD

**Issue by JasperDeLaat94** [RedpointGames/uet#82]
Symbols for Android are generated both by the 'Compile' and 'Pak and Stage' steps of the build process. However the compile step doesn't seem to take the new Timestamp into account, whereas the Pak and Stage step does, resulting in two different symbols being output:

![image](https://github.com/user-attachments/assets/33f2bbda-93cc-42de-aade-7e6276a58ba0)

**Comment by JasperDeLaat94** [comment]
I'm also starting to see that subsequent build invokations (using local executor as I don't have Gitlab) result in old symbols being tagged in subsequent builds.

**Comment by hach-que** [comment]
I'm guessing we might need to pass the version argument to the `<Compile>` tag as well.

The `DefaultPreBuild` implementation clears out the `Android`/`MetaQuest`/`GooglePlay` folders before build, but only for the new `MetaQuest` and `GooglePlay` platforms. That was to avoid it clearing out the `Android` folder when you didn't want it to, but it sounds like we might have to do it for normal `Android` as well due to the versioning stuff.
